experiment_name: force-train-general
train_objects: ['microwave-1', 'dishwasher-1']
test_objects: ['microwave-2', 'microwave-3', 'microwave-4']
run_id: 7

force_policy: 
  gamma: 0.99
  algorithm: ddpg
  lr: 1.0e-4
  batch_size: 200
  polyak: 0.995 
  noise_clip: 1. 
  policy_decay: 2. 
  checkpoint_path: 'checkpoints/revolute_object_general_test'

environment:
  max_timesteps: 200
  action_repeat: 1 

robot:
  name: Panda
  action_scale: 0.1 # The scale of action execution 
  # interaction stuff
  kp_interaction: 5
  interaction_timesteps: 10 
  interaction_action_scale: 0.05
  kp_execution: 150 
  interaction_directions: ['forward', 'backward', 'left', 'right']